mocap4r2_gt:
  ros__parameters:
    root_frame: 'map'
    robot_frame: 'base_link'
    mocap_frame: 'base_mocap'
    rigid_body_name: 'jackal aligned.jackal aligned'
    rigid_body_topic: '/rigid_bodies'
    odometry_topic: '/vicon/odom'
    init_mocap4r2_xyzrpy: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    covariance:
      pose: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      twist: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    # alpha: 0.1 # for exponential moving average
